<div class="container-max">
  <img src="images/others/menu-card.jpg" class="menu-card" alt="Speisekarte">
</div>


<div class="container-max">
  <div class="container">
    <div class="parent">
    <div class=><img src="images/dishes/dish1.png" alt="dish1" class="dish-image"></div>
    <div class="dishes-text-reverse">Ein Geschmacksfeuerwerk:<br><span class="bold">UNSER PAD THAI</span> Ein Erlebnis, das dich auf eine kulinarische Reise nach Thailand entführt. Zarte, in feuriger Marinade geschwenkte Garnelen treffen auf perfekt gegarte Reisnudeln, die mit knackigen Erdnüssen, frischem Koriander und zarten Frühlingszwiebeln zu einem harmonischen Tanz der Aromen verschmelzen. Die spritzige Limette und knackige Sojasprossen runden das Geschmackserlebnis mit einer aufregenden Frische ab – eine unvergleichliche Mischung aus süß, sauer, salzig und leicht scharf. Ein absolutes Muss für Genießer, die das Besondere suchen!</div>
    <div class="dishes-food"><img src="images/dishes/dish2.png" alt="dish2" class="dish-image"></div>
    <div class="dishes-text">Ein Fest für die Sinne:<br><span class="bold">UNSER GRILLSTEAK & GEMÜSE </span> Tauche ein in ein kulinarisches Erlebnis voller Raffinesse und Geschmack. Zart gegrilltes Steak mit charakteristischen Grillstreifen und rauchiger Note trifft auf eine herzhafte Begleitung aus goldbraun gerösteten Kartoffeln, karamellisierten Möhren und aromatischen Pilzen. Ein Zweig frischer Rosmarin rundet das Gericht ab und verleiht ihm einen mediterranen Touch. Jeder Bissen vereint würzige, süßliche und deftige Nuancen – wie ein Sommerabend auf dem Teller.</div>
    <div class="dishes-food"><img src="images/dishes/dish3.png" alt="dish3" class="dish-image"></div>
    <div class="dishes-text">Ein Aromen-Konzert:<br><span class="bold">UNSER HERZLICHES BOWL-ERLEBNIS</span> Erlebe eine sinfonische Komposition aus rauchig gegrillten Würstchen, perfekt gekochten Eiern, die in ihrer Halbierung zarte Cremigkeit versprühen, und sonnengereiften Tomaten, die Frische und Farbe in das Ensemble bringen. Knackige Bohnen und rote Zwiebelscheiben fügen dem Geschmacksbild einen würzigen, lebendigen Takt hinzu, während ein Stück gegrilltes Fleisch – gekrönt mit frischer Petersilie – die Melodie zu einem kraftvollen Finale erhebt. Jeder Löffel ist ein harmonisches Zusammenspiel von Aromen, das den Gaumen umschmeichelt und Lust auf mehr macht.</div>
    <div class="dishes-food"><img src="images/dishes/dish4.png" alt="dish4" class="dish-image"></div>
    <div class="dishes-text-reverse">Ein Farbenrausch der Fermentation:<br><span class="bold">UNSER KIMCHI-KINO</span> Tauche ein in ein Geschmackserlebnis, das Tradition und Moderne kühn vereint. Die fein fermentierten Kohlblätter umhüllt von einer pikant-scharfen Chili-Soße treffen auf knackige Radieschen und frischen Koriander – ein harmonischer Tanz aus feurigen Aromen und erfrischenden Noten. Geröstete Sesamkörner verleihen jedem Löffel eine subtile Nussigkeit, während die perfekte Balance aus Schärfe, Säure und einer dezenten Süße den Gaumen verführt. Ein absolutes Must-Have für alle, die den authentischen Kick der koreanischen Küche lieben!</div>
    <div class="dishes-food"><img src="images/dishes/dish5.png" alt="dish5" class="dish-image"></div>
    <div class="dishes-text">Ein Orchester der Aromen:<br><span class="bold">UNSER PAD THAI</span> Erlebe ein kulinarisches Meisterwerk, das Dich mitten ins Herz Fernosts entführt. Perfekt gegarte Reisnudeln umspielen zarte Garnelen, während ein samtiges Eigerinn im Zusammenspiel mit knackigen Sojasprossen, frischem Koriander und gerösteten Erdnüssen eine harmonische Melodie aus süßen, sauren und leicht scharfen Noten entfaltet. Ein Spritzer Limette und ein Hauch Chili verleihen dem Gericht den letzten, belebenden Takt – ein Genusserlebnis, das Deine Sinne zum Tanzen bringt.</div>
    <div class="dishes-food"><img src="images/dishes/dish6.png" alt="dish6" class="dish-image"></div>
    <div class="dishes-text">Ein Fest der Frische:<br><span class="bold">UNSER SHRIMP PAD THAI</span> Tauche ein in ein kulinarisches Abenteuer, in dem goldene Reisnudeln mit saftig gebratenen Garnelen ihren Tanz beginnen. Frisch-knackige Bohnensprossen, leuchtend grüne Zwiebelstreifen und geröstete Erdnüsse verschmelzen zu einem harmonischen Zusammenspiel der Aromen. Ein Hauch von feinem Koriander und zarte Scheiben roter Chili sorgen für den nötigen Kick, während ein Spritzer Limette das Ensemble mit erfrischender Lebendigkeit krönt. Jeder Bissen ist ein unwiderstehlicher Moment, der Tradition und moderne Raffinesse zu einem unvergesslichen Fest der Sinne vereint.</div>
    <div class="dishes-food"><img src="images/dishes/dish7.png" alt="dish7" class="dish-image"></div>
    <div class="dishes-text-reverse">Ein Tanz der Aromen:<br><span class="bold">UNSER CHICKEN WOK NOODLES</span> Erlebe, wie zarte, goldbraun gebratene Nudeln in perfekter Harmonie mit saftig gegrilltem Hähnchen und einer bunten Vielfalt knackigen Gemüses verschmelzen. Leuchtende Paprikastreifen, feine Karottenwürfel und knackige Frühlingszwiebeln entfalten gemeinsam ein lebendiges Farbenspiel und ein intensiv frisches Aroma. Ein Spritzer würzige Sojasauce und ein Hauch aromatisches Sesamöl vollenden das Geschmackserlebnis – ein faszinierender Tanz aus traditioneller Ferne und moderner Raffinesse, der jeden Bissen zu einem unvergesslichen Fest für die Sinne macht.</div>
    <div class="dishes-food"><img src="images/dishes/dish8.png" alt="dish8" class="dish-image"></div>
    <div class="dishes-text">Ein Feuerwerk der Aromen:<br><span class="bold">UNSERE GRILL-TACOS</span> Tauche ein in ein Geschmackserlebnis, das dich direkt in die Welt mexikanischer Leidenschaft entführt. Zart gegrillte Rindfleischstreifen verschmelzen harmonisch mit leuchtend roten und sonnengelben Paprikastreifen, während ein frischer Hauch knackiger Petersilie das Ganze krönt. Jeder Biss bietet ein Zusammenspiel aus rauchigen, würzigen und erfrischenden Noten – ein visuelles und kulinarisches Highlight, das Lust auf mehr macht.</div>
    <div class="dishes-food"><img src="images/dishes/dish9.png" alt="dish9" class="dish-image"></div>
    <div class="dishes-text">Ein Tanz der Schärfe:<br><span class="bold">UNSER KOREANISCHES JJIGAE</span> Lass dich entführen in ein Feuerwerk intensiver Aromen, das dich mitten ins Herz der koreanischen Küche katapultiert. In einer leuchtend roten Brühe, die von einer verführerischen Kombination aus Chili und fermentierten Nuancen pulsiert, verschmelzen zarte Tofuwürfel, knackige Zwiebelstreifen und frische grüne Akzente zu einem harmonischen Zusammenspiel aus feuriger Schärfe und umami. Ein feiner Hauch von geröstetem Sesam und die spritzige Frische von gehackten Frühlingszwiebeln verleihen jedem Löffel den besonderen Kick – ein kulinarisches Erlebnis, das deine Sinne auf eine unvergessliche Reise schickt.</div>
    </div>
  </div>
</div>